services:
  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - TZ=America/Sao_Paulo
    command:
      - redis-server
      - '--bind'
      - redis
      - '--port'
      - '6379'
      - '--notify-keyspace-events'
      - Ex
    ports:
      - 6379:6379